a=int(input("enter a number"))
b=int(input("enter a number"))
c=(a>b)and(a==b)
print(c)
c=(a<b)and(a==b)
print(c)
c=(a>b)or(a==b)
print(c)
c=(a<b)or(a==b)
print(c)
c=(not(a>b))and(a==b)
print(c)
c=(not((a<b)and(a==b)))
print(c)